using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Desktop.Extensions;
using Desktop.ViewModels;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Services;
using Google.Apis.YouTube.v3;
using Google.Apis.YouTube.v3.Data;

namespace Desktop.Services;

public static class YoutubeService
{
    private static YouTubeService YouTubeService
    {
        get
        {
            if (field is null) InitYouTubeServiceAsync().Wait();
            return field!;
        }
        set;
    }

    public static async Task<IEnumerable<FileItemViewModel>> GetAllVideosWithoutCustomCaptions(bool privateVideos = false)
    {
        var allVideoIds = await GetAllVideoIdsAsync(privateVideos);
        return await allVideoIds.SelectManyAsync(async id =>
        {
            var captions = await GetLanguagesWithAutoGeneratedCaptions(id);
            return captions.Select(c => new FileItemViewModel($"yt:{id}") { Language = c.Snippet.Language });
        });
    }

    public static async Task DownloadAudio(string id, string outputPath, CancellationToken ct = default)
    {
        Directory.CreateDirectory(outputPath);

        string[] arguments =
        [
            "-x",
            $"--ffmpeg-location \"{ConfigService.Config.FfmpegLocation}\"",
            "-f bestaudio",
            $"-o \"{outputPath}/%(title)s.%(ext)s\"",
            $"https://youtu.be/{id}"
        ];

        var startInfo = new ProcessStartInfo
        {
            FileName = $"{ConfigService.Config.YtdlpLocation}/yt-dlp.exe",
            Arguments = string.Join(' ', arguments),
            RedirectStandardError = true,
            RedirectStandardOutput = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var proc = new Process();
        proc.StartInfo = startInfo;
        proc.EnableRaisingEvents = true;

        proc.ErrorDataReceived += (s, a) => Console.WriteLine(a.Data);
        proc.OutputDataReceived += (s, a) => Console.WriteLine("ERROR: " + a.Data);

        proc.Start();
        proc.BeginErrorReadLine();
        proc.BeginOutputReadLine();

        await proc.WaitForExitAsync(ct);

        // proc.ErrorDataReceived -= FfmpegInfoLogger;
        // proc.OutputDataReceived -= FfmpegInfoLogger;

        if (proc.ExitCode != 0) throw new Exception("YT-DLP Exitcode: " + proc.ExitCode);
    }

    private static async Task<IEnumerable<string>> GetAllVideoIdsAsync(bool privateVideos)
    {
        const string privateStatus = "private";

        // get "uploads" Playlist
        var request = YouTubeService.Channels.List("contentDetails");
        request.Mine = true;
        var response = await request.ExecuteAsync();
        var uploadsPlaylistId = response.Items[0].ContentDetails.RelatedPlaylists.Uploads;

        // get VideoIDs from Playlist
        var videoIds = new List<string>();
        string? nextToken = null;
        do
        {
            var req = YouTubeService.PlaylistItems.List("contentDetails,status");
            req.PlaylistId = uploadsPlaylistId;
            req.MaxResults = 50;
            req.PageToken = nextToken;

            var resp = await req.ExecuteAsync();

            var ids = resp.Items
                .Where(i => privateVideos || !string.Equals(i.Status?.PrivacyStatus, privateStatus))
                .Select(item => item.ContentDetails.VideoId);
            videoIds.AddRange(ids);
            nextToken = resp.NextPageToken;
        } while (nextToken != null);

        return videoIds;
    }

    private static async Task InitYouTubeServiceAsync(CancellationToken ct = default)
    {
        UserCredential credential;

        await using (var stream = new FileStream("client_secret.json", FileMode.Open, FileAccess.Read))
        {
            string[] scopes =
            [
                YouTubeService.Scope.YoutubeForceSsl, // read captions
                YouTubeService.Scope.YoutubeUpload // upload captions
            ];
            var clientSecret = await GoogleClientSecrets.FromStreamAsync(stream, ct);
            const string userId = "YourUserID"; //TODO what does it do?
            credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(clientSecret.Secrets, scopes, userId, ct);
        }

        YouTubeService = new YouTubeService(new BaseClientService.Initializer
        {
            HttpClientInitializer = credential,
            ApplicationName = "AutoCaption"
        });
    }

    private static async Task<IEnumerable<Caption>> GetLanguagesWithAutoGeneratedCaptions(string videoId)
    {
        const string autoGeneratedCaptionKind = "asr";

        var request = YouTubeService.Captions.List("snippet", videoId);
        var response = await request.ExecuteAsync();

        //TODO check audio languages
        //TODO check english always

        return response.Items.Where(c => c.Snippet.TrackKind.Equals(autoGeneratedCaptionKind));
    }

    private static async Task UploadCaptionAsync(string videoId, string language, string path)
    {
        var caption = new Caption
        {
            Snippet = new CaptionSnippet
            {
                VideoId = videoId,
                Language = language,
                Name = "AutoCaption" //TODO what does it do?
            }
        };

        var extension = Path.GetExtension(path);
        await using var fs = new FileStream(path, FileMode.Open, FileAccess.Read);
        var insert = YouTubeService.Captions.Insert(caption, "snippet", fs, $"text/{extension}");
        await insert.UploadAsync();
    }
}